language: node_js
node_js:
  - '8'
sudo: false
cache:
  directories:
    - node_modules
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then deploy/script/publish.sh v$TRAVIS_BUILD_NUMBER ; fi
