FROM node:8.9.1-slim

RUN apt-get update && apt-get install tzdata
RUN mkdir /src

WORKDIR /src
ADD package.json /src/package.json
RUN npm install

ADD deploy/wait-for-it.sh /wait-for-it.sh
RUN chmod a+x /wait-for-it.sh

EXPOSE 8000

CMD npm run ft