version: '3.4'

services:
    db:
        image: mysql:5.7
        restart: always
        command: --init-file /db/init.sql --character-set-server=utf8
        environment:
          - MYSQL_ROOT_PASSWORD=example
        ports:
          - "33061:3306"
        volumes:
          - "./db:/db"

    api:
        build:
          context: .
          dockerfile: Dockerfile-dev
        entrypoint: /wait-for-it.sh db:3306 -- 
        command: npm run dev
        ports:
            - 8000:8000
        volumes:
          - ".:/src"
          - "./node_modules:/src/node_modules"
        environment:
          - ZFT_RDS_HOST=db
          - ZFT_RDS_PORT=3306
          - ZFT_RDS_USERNAME=root
          - ZFT_RDS_PASSWORD=example
          - ZFT_RDS_DATABASE=zft
          - AMAPKEY
          - MONGOURL
          - EMRead
          - EMWrite
        depends_on:
          - db