version: '3.4'

services:
    db:
        image: mysql:5.7
        restart: always
        command: --init-file /db/init.sql --character-set-server=utf8
        environment:
          - MYSQL_ROOT_PASSWORD=example
        ports:
          - "33061:3306"
        volumes:
          - "./db:/db"

    api:
        build:
          context: .
          dockerfile: Dockerfile-dev
        entrypoint: /wait-for-it.sh db:3306 -- 
        command: npm run dev
        ports:
            - 8000:8000
        volumes:
          - ".:/src"
          - "./node_modules:/src/node_modules"
        environment:
          - ZFT_AMAP_KEY
          - ZFT_MONGO_URL
          - ZFT_EM_READ=[{"host":"db","port":3306,"username":"root","password":"example","database":"zft"}]
          - ZFT_EM_WRITE={"host":"db","port":3306,"username":"root","password":"example","database":"zft"}
        depends_on:
          - db