version: '3.4'

services:
    db:
        image: mysql:5.7
        restart: always
        command: --init-file /db/init.sql --character-set-server=utf8
        environment:
          - MYSQL_ROOT_PASSWORD=example
        ports:
          - "33061:3306"
        volumes:
          - "./db:/db"
    mongo:
        image: registry.docker-cn.com/library/mongo:latest
        command: mongod --smallfiles
        ports:
          - 27017:27017
        depends_on:
          - mongo_seed

    redis:
        image: registry.docker-cn.com/library/redis:4
        restart: always
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
          - "/private/etc/redis/redis_docker.conf:/usr/local/etc/redis/redis.conf"
        ports:
          - 6379:6379

    mongo_seed:
        build:
          context: ./deploy/
          dockerfile: docker/Dockerfile_mongo_seed
        entrypoint: /wait-for-it.sh mongo:27017 --
        command: mongoimport --host mongo --db local --collection projects --type json --file /init.json

    api:
        build:
          context: .
          dockerfile: Dockerfile-dev
        entrypoint: /wait-for-it.sh db:3306 -- 
        command: npm run dev
        ports:
            - 8000:8000
        volumes:
          - ".:/src"
          - "./node_modules:/src/node_modules"
        environment:
          - ZFT_AMAP_KEY
          - ZFT_MONGO_URL=mongodb://mongo:27017/local
          - ZFT_EM_READ=[{"host":"db","port":3306,"username":"root","password":"example","database":"zft"}]
          - ZFT_EM_WRITE={"host":"db","port":3306,"username":"root","password":"example","database":"zft"}
          - MSGQUEUE_HOST
          - MSGQUEUE_PORT
          - MSGQUEUE_PASSWD
        depends_on:
          - db
          - mongo
          - redis